### ISSUE TITLE
Error finding exif property name

### ISSUE THREAD

**Issue by nanihadesuka** [lluissm/media-renamer#14]
OS: Windows 10

````cmd
$ media-renamer.exe -v -c config.yml ./Photos-001
2022/09/23 20:34:34 Error renaming could not find information in metadata for file Photos-001\IMG20220717162959.jpg

````

On the photo detail properties that windows shows there is the exif property ` Date taken:  17/07/2022 16:29`  but seems is not found?

On the attachment there is the config.yml and the photo.jpg

[photo_and_config.zip](https://github.com/lluissm/media-renamer/files/9636379/photo_and_config.zip)

**Comment by lluissm** [comment]
Hi @nanihadesuka ,

Date taken is the name that Windows file explorer is showing for the column but not the name of the property inside the picture.

If you check the exif data, you will see that the name of the property is `Create Date`.

`$ exiftool ~/Downloads/photo_and_config/Photos-001/IMG20220717162959.jpg`

<img width="994" alt="Screenshot 2022-09-23 at 21 47 51" src="https://user-images.githubusercontent.com/5585708/192046009-c272b3d1-287e-4fab-90d0-89f7ae84bbf4.png">

So the correct configuration would be:

```yml
- extension: ".jpg"
  dateFields:
    - name: "CreateDate"
      dateFormat: "2006:01:02 15:04:05"
```

I will add it soon to the default config when I test more file types.

**Comment by nanihadesuka** [comment]
I see, it's working as expected now.

Might be a good idea to also show a different error message when the `dateFormat` doesn't match.
I see the same "not find information metadata" error if I have
` dateFormat: "2006:01:02 15:04:05-07:00"` :
but with 
` dateFormat: "2006:01:02 15:04:05"`  👍 
works, which is confusing.
